export const sentences = {
  hate: [
    "Ah, the passion in your 'hate' is almost... romantic.",
    "Hate? Sounds more like a love story in disguise!",
    "The line between love and hate is really blurry, isn't it?",
    "Sure, sure... we all know 'hate' is just love playing hard to get.",
    "That’s some fiery 'hate'—almost feels like burning love!",
    "You're hating with so much energy, it’s practically a compliment!",
    "Funny how this 'hate' feels a lot like admiration on a bad day.",
    "Are you sure it's hate? Because that was a little too passionate!",
    "Wow, that much 'hate' could only come from someone who cares... deeply.",
    "Your 'hate' is just love wearing a sarcastic disguise!",
    "Hate? Please, that's just love with extra drama.",
    "I see your 'hate' is really just love that needs a timeout.",
    "The intensity of this 'hate' feels suspiciously like affection!",
    "All that 'hate'—you’re really just one romantic gesture away!",
    "Your 'hate' is giving off some serious secret admirer vibes.",
    "Hate as passionately as this, and you might as well write them a love letter!",
    "That’s the most loving 'hate' I’ve ever seen!",
    "Deep down, we all know that ‘hate’ is just love dressed up for Halloween.",
    "Keep 'hating' like this, and you might accidentally fall in love.",
    "Wow, even your hate comes with a side of affection!",
  ],
  love: [
    "Awww, someone's heart just grew three sizes!",
    "Look at you, spreading love like confetti!",
    "Cue the violins, we’ve got a romantic over here!",
    "Oh wow, who knew you had such a soft side?",
    "You’ve officially leveled up to 'Certified Lovebug'.",
    "Quick, someone bottle this affection and sell it!",
    "Is this love? Or just a sugar rush?",
    "Look at you, melting hearts left and right!",
    "Hold on, did you just turn into a Hallmark card?",
    "I guess Cupid’s arrow found its mark!",
    "Whoa, you’re practically radiating rainbows right now!",
    "Someone’s in love – cue the cheesy love songs!",
    "That was so sweet, I think I got a cavity!",
    "Your heart’s on fire, but in a non-emergency way!",
    "You just sprinkled some serious love vibes over here.",
    "This level of affection should come with a warning label!",
    "You’re basically a walking heart emoji right now.",
    "Swoon alert! Somebody’s got the love bug!",
    "Are you sure this isn't a rom-com scene?",
    "I hope you didn’t just break the internet with all that love!",
  ],
};
